
type
  XID* = culong
  Mask* = culong
  Atom* = culong
  VisualID* = culong
  Time* = culong

  Drawable* = XID
  Window* = XID
  Font* = XID
  Pixmap* = XID
  Cursor* = XID
  Colormap* = XID
  GContext* = XID
  KeySym* = XID
  XSyncCounter* = distinct XID

  KeyCode* = char

  PropMode* {.size: int32.sizeof.} = enum
    pmReplace = 0
    pmPrepend = 1
    pmAppend = 2

  Status* = enum
    success = 0
    badRequest = 1
    badValue = 2
    badWindow = 3
    badPixmap = 4
    badAtom = 5
    badCursor = 6
    badFont = 7
    badMatch = 8
    badDrawable = 9
    badAccess = 10
    badAlloc = 11
    badColor = 12
    badGC = 13
    badIDChoice = 14
    badName = 15
    badLength = 16
    badImplementation = 17

  ByteOrder* = enum
    leftToRight = 0
    rightToLeft = 1

  RevertTo* {.size: int32.sizeof.} = enum
    rtNone = 0
    rtRoot = 1
    rtParent = 2

const
  ParentRelative* = 1
  CopyFromParent* = 0
  PointerWindow* = 0
  InputFocus* = 1
  PointerRoot* = 1
  AnyPropertyType* = 0
  AnyKey* = 0
  AnyButton* = 0
  AllTemporary* = 0
  CurrentTime* = 0
  NoSymbol* = 0
  NoEventMask* = 0
  KeyPressMask* = 1 shl 0
  KeyReleaseMask* = 1 shl 1
  ButtonPressMask* = 1 shl 2
  ButtonReleaseMask* = 1 shl 3
  EnterWindowMask* = 1 shl 4
  LeaveWindowMask* = 1 shl 5
  PointerMotionMask* = 1 shl 6
  PointerMotionHintMask* = 1 shl 7
  Button1MotionMask* = 1 shl 8
  Button2MotionMask* = 1 shl 9
  Button3MotionMask* = 1 shl 10
  Button4MotionMask* = 1 shl 11
  Button5MotionMask* = 1 shl 12
  ButtonMotionMask* = 1 shl 13
  KeymapStateMask* = 1 shl 14
  ExposureMask* = 1 shl 15
  VisibilityChangeMask* = 1 shl 16
  StructureNotifyMask* = 1 shl 17
  ResizeRedirectMask* = 1 shl 18
  SubstructureNotifyMask* = 1 shl 19
  SubstructureRedirectMask* = 1 shl 20
  FocusChangeMask* = 1 shl 21
  PropertyChangeMask* = 1 shl 22
  ColormapChangeMask* = 1 shl 23
  OwnerGrabButtonMask* = 1 shl 24
  LASTEvent* = 36
  ShiftMask* = 1 shl 0
  LockMask* = 1 shl 1
  ControlMask* = 1 shl 2
  Mod1Mask* = 1 shl 3
  Mod2Mask* = 1 shl 4
  Mod3Mask* = 1 shl 5
  Mod4Mask* = 1 shl 6
  Mod5Mask* = 1 shl 7
  ShiftMapIndex* = 0
  LockMapIndex* = 1
  ControlMapIndex* = 2
  Mod1MapIndex* = 3
  Mod2MapIndex* = 4
  Mod3MapIndex* = 5
  Mod4MapIndex* = 6
  Mod5MapIndex* = 7
  Button1Mask* = 1 shl 8
  Button2Mask* = 1 shl 9
  Button3Mask* = 1 shl 10
  Button4Mask* = 1 shl 11
  Button5Mask* = 1 shl 12
  AnyModifier* = 1 shl 15
  Button1* = 1
  Button2* = 2
  Button3* = 3
  Button4* = 4
  Button5* = 5
  NotifyNormal* = 0
  NotifyGrab* = 1
  NotifyUngrab* = 2
  NotifyWhileGrabbed* = 3
  NotifyHint* = 1
  NotifyAncestor* = 0
  NotifyVirtual* = 1
  NotifyInferior* = 2
  NotifyNonlinear* = 3
  NotifyNonlinearVirtual* = 4
  NotifyPointer* = 5
  NotifyPointerRoot* = 6
  NotifyDetailNone* = 7
  VisibilityUnobscured* = 0
  VisibilityPartiallyObscured* = 1
  VisibilityFullyObscured* = 2
  PlaceOnTop* = 0
  PlaceOnBottom* = 1
  FamilyInternet* = 0
  FamilyDECnet* = 1
  FamilyChaos* = 2
  FamilyInternet6* = 6
  FamilyServerInterpreted* = 5
  PropertyNewValue* = 0
  PropertyDelete* = 1
  ColormapUninstalled* = 0
  ColormapInstalled* = 1
  GrabModeSync* = 0
  GrabModeAsync* = 1
  GrabSuccess* = 0
  AlreadyGrabbed* = 1
  GrabInvalidTime* = 2
  GrabNotViewable* = 3
  GrabFrozen* = 4
  AsyncPointer* = 0
  SyncPointer* = 1
  ReplayPointer* = 2
  AsyncKeyboard* = 3
  SyncKeyboard* = 4
  ReplayKeyboard* = 5
  AsyncBoth* = 6
  SyncBoth* = 7
  FirstExtensionError* = 128
  LastExtensionError* = 255
  InputOutput* = 1
  InputOnly* = 2
  CwBackPixmap* = 1 shl 0
  CwBackPixel* = 1 shl 1
  CwBorderPixmap* = 1 shl 2
  CwBorderPixel* = 1 shl 3
  CwBitGravity* = 1 shl 4
  CwWinGravity* = 1 shl 5
  CwBackingStore* = 1 shl 6
  CwBackingPlanes* = 1 shl 7
  CwBackingPixel* = 1 shl 8
  CwOverrideRedirect* = 1 shl 9
  CwSaveUnder* = 1 shl 10
  CwEventMask* = 1 shl 11
  CwDontPropagate* = 1 shl 12
  CwColormap* = 1 shl 13
  CwCursor* = 1 shl 14
  CwX* = 1 shl 0
  CwY* = 1 shl 1
  CwWidth* = 1 shl 2
  CwHeight* = 1 shl 3
  CwBorderWidth* = 1 shl 4
  CwSibling* = 1 shl 5
  CwStackMode* = 1 shl 6
  ForgetGravity* = 0
  NorthWestGravity* = 1
  NorthGravity* = 2
  NorthEastGravity* = 3
  WestGravity* = 4
  CenterGravity* = 5
  EastGravity* = 6
  SouthWestGravity* = 7
  SouthGravity* = 8
  SouthEastGravity* = 9
  StaticGravity* = 10
  UnmapGravity* = 0
  NotUseful* = 0
  WhenMapped* = 1
  Always* = 2
  IsUnmapped* = 0
  IsUnviewable* = 1
  IsViewable* = 2
  SetModeInsert* = 0
  SetModeDelete* = 1
  DestroyAll* = 0
  RetainPermanent* = 1
  RetainTemporary* = 2
  Above* = 0
  Below* = 1
  TopIf* = 2
  BottomIf* = 3
  Opposite* = 4
  RaiseLowest* = 0
  LowerHighest* = 1
  GXclear* = 0x00000000
  GXand* = 0x00000001
  GXandReverse* = 0x00000002
  GXcopy* = 0x00000003
  GXandInverted* = 0x00000004
  GXnoop* = 0x00000005
  GXxor* = 0x00000006
  GXor* = 0x00000007
  GXnor* = 0x00000008
  GXequiv* = 0x00000009
  GXinvert* = 0x0000000A
  GXorReverse* = 0x0000000B
  GXcopyInverted* = 0x0000000C
  GXorInverted* = 0x0000000D
  GXnand* = 0x0000000E
  GXset* = 0x0000000F
  LineSolid* = 0
  LineOnOffDash* = 1
  LineDoubleDash* = 2
  CapNotLast* = 0
  CapButt* = 1
  CapRound* = 2
  CapProjecting* = 3
  JoinMiter* = 0
  JoinRound* = 1
  JoinBevel* = 2
  FillSolid* = 0
  FillTiled* = 1
  FillStippled* = 2
  FillOpaqueStippled* = 3
  EvenOddRule* = 0
  WindingRule* = 1
  ClipByChildren* = 0
  IncludeInferiors* = 1
  Unsorted* = 0
  YSorted* = 1
  YXSorted* = 2
  YXBanded* = 3
  CoordModeOrigin* = 0
  CoordModePrevious* = 1
  Complex* = 0
  Nonconvex* = 1
  Convex* = 2
  ArcChord* = 0
  ArcPieSlice* = 1
  GCFunction* = 1 shl 0
  GCPlaneMask* = 1 shl 1
  GCForeground* = 1 shl 2
  GCBackground* = 1 shl 3
  GCLineWidth* = 1 shl 4
  GCLineStyle* = 1 shl 5
  GCCapStyle* = 1 shl 6
  GCJoinStyle* = 1 shl 7
  GCFillStyle* = 1 shl 8
  GCFillRule* = 1 shl 9
  GCTile* = 1 shl 10
  GCStipple* = 1 shl 11
  GCTileStipXOrigin* = 1 shl 12
  GCTileStipYOrigin* = 1 shl 13
  GCFont* = 1 shl 14
  GCSubwindowMode* = 1 shl 15
  GCGraphicsExposures* = 1 shl 16
  GCClipXOrigin* = 1 shl 17
  GCClipYOrigin* = 1 shl 18
  GCClipMask* = 1 shl 19
  GCDashOffset* = 1 shl 20
  GCDashList* = 1 shl 21
  GCArcMode* = 1 shl 22
  GCLastBit* = 22
  FontLeftToRight* = 0
  FontRightToLeft* = 1
  FontChange* = 255
  XYBitmap* = 0
  XYPixmap* = 1
  ZPixmap* = 2
  AllocNone* = 0
  AllocAll* = 1
  DoRed* = 1 shl 0
  DoGreen* = 1 shl 1
  DoBlue* = 1 shl 2
  CursorShape* = 0
  TileShape* = 1
  StippleShape* = 2
  AutoRepeatModeOff* = 0
  AutoRepeatModeOn* = 1
  AutoRepeatModeDefault* = 2
  LedModeOff* = 0
  LedModeOn* = 1
  KBKeyClickPercent* = 1 shl 0
  KBBellPercent* = 1 shl 1
  KBBellPitch* = 1 shl 2
  KBBellDuration* = 1 shl 3
  KBLed* = 1 shl 4
  KBLedMode* = 1 shl 5
  KBKey* = 1 shl 6
  KBAutoRepeatMode* = 1 shl 7
  MappingSuccess* = 0
  MappingBusy* = 1
  MappingFailed* = 2
  MappingModifier* = 0
  MappingKeyboard* = 1
  MappingPointer* = 2
  DontPreferBlanking* = 0
  PreferBlanking* = 1
  DefaultBlanking* = 2
  DisableScreenSaver* = 0
  DisableScreenInterval* = 0
  DontAllowExposures* = 0
  AllowExposures* = 1
  DefaultExposures* = 2
  ScreenSaverReset* = 0
  ScreenSaverActive* = 1
  HostInsert* = 0
  HostDelete* = 1
  EnableAccess* = 1
  DisableAccess* = 0
  StaticGray* = 0
  GrayScale* = 1
  StaticColor* = 2
  PseudoColor* = 3
  TrueColor* = 4
  DirectColor* = 5

const
  xaPrimary* = Atom 1
  xaSecondary* = Atom 2
  xaArc* = Atom 3
  xaAtom* = Atom 4
  xaBitmap* = Atom 5
  xaCardinal* = Atom 6
  xaColormap* = Atom 7
  xaCursor* = Atom 8
  xaCutBuffer0* = Atom 9
  xaCutBuffer1* = Atom 10
  xaCutBuffer2* = Atom 11
  xaCutBuffer3* = Atom 12
  xaCutBuffer4* = Atom 13
  xaCutBuffer5* = Atom 14
  xaCutBuffer6* = Atom 15
  xaCutBuffer7* = Atom 16
  xaDrawable* = Atom 17
  xaFont* = Atom 18
  xaInteger* = Atom 19
  xaPixmap* = Atom 20
  xaPoint* = Atom 21
  xaRectangle* = Atom 22
  xaResourceManager* = Atom 23
  xaRgbColorMap* = Atom 24
  xaRgbBestMap* = Atom 25
  xaRgbBlueMap* = Atom 26
  xaRgbDefaultMap* = Atom 27
  xaRgbGrayMap* = Atom 28
  xaRgbGreenMap* = Atom 29
  xaRgbRedMap* = Atom 30
  xaString* = Atom 31
  xaVisualid* = Atom 32
  xaWindow* = Atom 33
  xaWmCommand* = Atom 34
  xaWmHints* = Atom 35
  xaWmClientMachine* = Atom 36
  xaWmIconName* = Atom 37
  xaWmIconSize* = Atom 38
  xaWmName* = Atom 39
  xaWmNormalHints* = Atom 40
  xaWmSizeHints* = Atom 41
  xaWmZoomHints* = Atom 42
  xaMinSpace* = Atom 43
  xaNormSpace* = Atom 44
  xaMaxSpace* = Atom 45
  xaEndSpace* = Atom 46
  xaSuperscriptX* = Atom 47
  xaSuperscriptY* = Atom 48
  xaSubscriptX* = Atom 49
  xaSubscriptY* = Atom 50
  xaUnderlinePosition* = Atom 51
  xaUnderlineThickness* = Atom 52
  xaStrikeoutAscent* = Atom 53
  xaStrikeoutDescent* = Atom 54
  xaItalicAngle* = Atom 55
  xaXHeight* = Atom 56
  xaQuadWidth* = Atom 57
  xaWeight* = Atom 58
  xaPointSize* = Atom 59
  xaResolution* = Atom 60
  xaCopyright* = Atom 61
  xaNotice* = Atom 62
  xaFontName* = Atom 63
  xaFamilyName* = Atom 64
  xaFullName* = Atom 65
  xaCapHeight* = Atom 66
  xaWmClass* = Atom 67
  xaWmTransientFor* = Atom 68
  xaLastPredefined* = Atom 68

var
  # These "constants" are not known at compile time,
  # but are poluatinged by x11 via initConstants().
  xaNetWMState*: Atom
  xaNetWMStateMaximizedHorz*: Atom
  xaNetWMStateMaximizedVert*: Atom
  xaWMState*: Atom
  xaNetWMIcon*: Atom
  xaNetWMStateHiden*: Atom
  xaNetWMStateFullscreen*: Atom
  xaNetWMName*: Atom
  xaUTF8String*: Atom
  xaNetWMIconName*: Atom
  xaWMDeleteWindow*: Atom
  xaNetWMSyncRequest*: Atom
  xaNetWMSyncRequestCounter*: Atom
  xaClipboard*: Atom
  xaWindyClipboardTargetProperty*: Atom
  xaTargets*: Atom
  xaText*: Atom
